### ISSUE TITLE
Test suite won't compile with gcc 4.8.4

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#40]
Hi,
  I'd like to run the test suite but I find that my gcc is failing to compile the intentionally incorrect asm code 'lock nop'. I can comment it out but that avoids the test. Perhaps there is a better way?
~~~
ajb@polly:/stuff/dosemu2.git/src/tests$ make
gcc -m32 -Wall -O2 -g -fno-strict-aliasing  -static -o test-i386 \
              ./test-i386.c ./test-i386-code16.S ./test-i386-vm86.S -lm
./test-i386.c: Assembler messages:
./test-i386.c:2075: Error: expecting lockable instruction after `lock'
make: *** [test-i386] Error 1
~~~

Code around line 2075 shows
~~~
    printf("lock nop exception:\n");                                            
    if (setjmp(jmp_env) == 0) {                                                 
        /* now execute an invalid instruction */                                
        asm volatile("lock nop");                                               
    }                                                                           
~~~

~~~
ajb@polly:/stuff/dosemu2.git/src/tests$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
~~~

**Comment by stsp** [comment]
Thanks.

**Comment by andrewbird** [comment]
Thanks, that's great.

**Comment by andrewbird** [comment]
Sorry to resurrect an old thread but it didn't seem worth a new one. When running `src/tests/test-i386.exe` on DOS what signifies success, is it just that it reaches the end without crashing, or is there something more obvious?

**Comment by stsp** [comment]
Ending w/o crash is a good sign, and in
fact, so far I only used it that way.
I think the proper use is to collect its
output on a real CPU (qemu/kvm should
do too, dosemu2/kvm is questionable),
and then compare the output with the
one from dosemu2/cpu-emu.

**Comment by andrewbird** [comment]
It seems we have compilation issues on Bionic 64bit machine at least.

32 bit version
~~~
ajb@bionic:/common/src2/dosemu2.git/src/tests$ make
gcc -m32 -Wall -O2 -g -fno-strict-aliasing -fno-pic -fno-pie  -o test-i386 test-i386.c test-i386-code16.S test-i386-vm86.S -lm
In file included from test-i386.c:28:0:
/usr/include/stdlib.h:25:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:11: recipe for target 'test-i386' failed
make: *** [test-i386] Error 1
~~~

and the 64 bit version

~~~
ajb@bionic:/common/src2/dosemu2.git/src/tests$ make test-x86_64
gcc -m64 -Wall -O2 -g -fno-strict-aliasing -fno-pic -fno-pie  -o test-x86_64 ./test-i386.c -lm
./test-i386.c:2384:1: warning: specifying vector types with __attribute__ ((mode)) is deprecated [-Wattributes]
 typedef int __m64 __attribute__ ((__mode__ (__V2SI__)));
 ^~~~~~~
./test-i386.c:2384:1: warning: use __attribute__ ((vector_size)) instead [-Wattributes]
./test-i386.c:2385:1: warning: specifying vector types with __attribute__ ((mode)) is deprecated [-Wattributes]
 typedef float __m128 __attribute__ ((__mode__(__V4SF__)));
 ^~~~~~~
./test-i386.c:2385:1: warning: use __attribute__ ((vector_size)) instead [-Wattributes]
/usr/bin/ld: /tmp/cc2P36GU.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'test-x86_64' failed
make: *** [test-x86_64] Error 1
~~~

**Comment by andrewbird** [comment]
Was missing multilib for the first issue, and now it compiles cleanly.

**Comment by stsp** [comment]
Ahh, makes sense!
So you don't need qemu/kvm.
You just get the reference output
from the natively compiled binary.

**Comment by andrewbird** [comment]
Well almost, 32 bit binary crashes on 64bit machine.
~~~
<snip>
larw: Z=1 1234f200
larl: Z=1 00c0f200
lslw: Z=1 12341fff
lsll: Z=1 00001fff
larw: Z=0 12345678
larl: Z=0 12345678
lslw: Z=0 12345678
lsll: Z=0 12345678
arplw A=1234567b B=0762123d R=1234567b z=0
arplw A=12345679 B=0762123f R=1234567b z=1
arplw A=12345679 B=0762123d R=12345679 z=0
Segmentation fault (core dumped)
~~~

64 bit binary won't link.

**Comment by andrewbird** [comment]
Crash is in the `test_code16()` function, so just commenting it out for now.

**Comment by andrewbird** [comment]
Excluding the `test_code16()` and line endings, the outputs are as follows [t1.zip](https://github.com/stsp/dosemu2/files/3854245/t1.zip)

**Comment by andrewbird** [comment]
actually scratch that, it's native / dosemu kvm! What cpuemu settings should I use!

**Comment by stsp** [comment]
The tests needs to be adjusted so that for
example for movs/stos/loads it would print
not the absolute values of esi/edi, but their
deltas. Otherwise you can't trivially diff it.

**Comment by stsp** [comment]
Could you please add also the multilib
build to travid?
`--with-target-bits-32` in configure.

**Comment by andrewbird** [comment]
Okay will do later. I also have some other travis changes I've been testing too.
