### ISSUE TITLE
carrier command doesn't work

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#922]
**Describe the bug**
Hangs at start.
Works on 1.4.

**To Reproduce**
Just run the game.

**Attach the binaries or provide an URL**
https://www.myabandonware.com/game/carrier-command-m6

**Comment by jschwartzenberg** [comment]
It's kind of tricky to bisect this. On Ubuntu 18.04 I'm often running into things like `configure: error: Cannot compile dosemu with stack protector enabled`. Do you have any tricks for this?

**Comment by stsp** [comment]
Please dont go past pre8 or pre7.
Lets identify the recent regressions first.

**Comment by jschwartzenberg** [comment]
In pre8 this one crashes in a different way:
![afbeelding](https://user-images.githubusercontent.com/877112/65385423-c54e7c00-dd2e-11e9-8c30-543ebeec95e0.png)

(pre7 runs into a compilation error on 18.04, with all these compilers getting stricter & stricter, we should possibly look into using docker to do bisecting)

**Comment by stsp** [comment]
Try clang when bisecting.
`CC=clang ./default-configure`.
But clang is not guaranteed to work.
I think it was unsupported in some of
our pre-alphas.
In fact when we fully switch to fdpp,
things will became pretty much unbisectable,
and that's scary.

**Comment by jschwartzenberg** [comment]
Are you interested in the bisect between working and the crash in pre8? I'll try to compile pre7 with clang.

**Comment by jschwartzenberg** [comment]
clang doesn't build pre7 either on 18.04.

**Comment by stsp** [comment]
> Are you interested in the bisect between working and the crash in pre8?

I do bu tI don't suppose its easy for you to do.
So the suggestion is to take up only those bisects
that regressed since pre8.

**Comment by jschwartzenberg** [comment]
Alright, I'll start with those at least and first see if any of the games still run in pre8.

**Comment by jschwartzenberg** [comment]
Runs for me in DOSEMU2 with FreeDOS, f9e9abd26376bc0538e23b649799cb5ea01db77f.

**Comment by stsp** [comment]
Yep.
All seems well.

**Comment by jschwartzenberg** [comment]
Doesn't break either when I revert dosemu, fdpp & comcom32 to the commits to the ones on the system on which it's broken.

**Comment by stsp** [comment]
But please try it on a system where volksvga
breaks, w/o any reverts.

**Comment by jschwartzenberg** [comment]
Yes, I did as well, then dosemu crashes. Or should I try updating dosemu2 to latest?

**Comment by stsp** [comment]
Yes, latest was crashing.

**Comment by jschwartzenberg** [comment]
Yep, still crashes on my other system. I updated everything to latest. What is your Linux version? Apart from all the hardware that is the main difference between my systems.

**Comment by stsp** [comment]
Will look-up later at home my linux version.
Hardware didn't change in my case, so we can
exclude that.

**Comment by stsp** [comment]
It would be great if you can fixate the "broken"
system and provide an ssh access to it.
I can't even imagine how the kernel could break
the particular games. It can break DPMI or KVM,
but it doesn't interact with real-mode games...

**Comment by jschwartzenberg** [comment]
I just updated all packages on it gave it a reboot and it's still broken there. That didn't update the major version of the kernel, just a patch update. It seems it's pretty stably not working there :)

**Comment by stsp** [comment]
So you claim its kernel?
Can you downgrade the kernel on the
system where it works fine?

**Comment by stsp** [comment]
Btw, by "fixate" I meant snapshot or backup it
so that the breakage can always be reproduced.
I didn't mean "fix it". :)

**Comment by jschwartzenberg** [comment]
Yeah I know, but I wanted to indicate it seems kind of fixated :)

**Comment by jschwartzenberg** [comment]
Nope, that's not it. I have it all running with the 4.15 kernel on this notebook. It's a bit trickier for me to provide SSH access, but maybe there's some command I can run with debugging?

It's curious you managed so solve the issue on your system. I just have it broken on one and working on the other :)

**Comment by stsp** [comment]
I didn't solve anything, it just have fixed itself.
Try copying dosemu binaries between machines.
You can move the entire build dir and run from there.
Maybe gcc update fixed some compilation bug?

**Comment by stsp** [comment]
Also try clang.

**Comment by jschwartzenberg** [comment]
I recompiled both today with a fully updated Ubuntu 18.04, so I can't imagine a compiler change to be the cause.

**Comment by stsp** [comment]
My kernel is currently 5.2.17-100.fc29.x86_64.
Dunno which one was when it didn't work.

One thing to try is `dosemu -vangrind` and
see if some error pops up.

**Comment by jschwartzenberg** [comment]
Seems not:
```
INFO: fdpp booting, this is very experimental!
ERROR: EMU86: error 2
==4362== 
==4362== HEAP SUMMARY:
==4362==     in use at exit: 346,353 bytes in 2,956 blocks
==4362==   total heap usage: 64,527 allocs, 61,571 frees, 79,619,716 bytes allocated
==4362== 
==4362== LEAK SUMMARY:
==4362==    definitely lost: 24,888 bytes in 10 blocks
==4362==    indirectly lost: 0 bytes in 0 blocks
==4362==      possibly lost: 43,292 bytes in 1,319 blocks
==4362==    still reachable: 278,173 bytes in 1,627 blocks
==4362==         suppressed: 0 bytes in 0 blocks
==4362== Rerun with --leak-check=full to see details of leaked memory
==4362== 
==4362== For counts of detected and suppressed errors, rerun with: -v
==4362== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 2 from 1)
```

**Comment by jschwartzenberg** [comment]
Hmm, I just discovered this:
```
Cannot run DPMI code natively for unknown reasons.
Please contact linux-msdos@vger.kernel.org.
Set $_cpu_emu="full" or "fullsim" to avoid this message.
```

I didn't notice that before or is that due to valgrind?

**Comment by andrewbird** [comment]
@jschwartzenberg did you run valgrind from the dosemu startup script as `dosemu -valgrind` it should setup the dosemu.conf properly for it.

**Comment by jschwartzenberg** [comment]
Yep, I did exactly like that.

**Comment by stsp** [comment]
Is it a cpu without kvm?

**Comment by stsp** [comment]
In either case, please just bisect
the problem. It works with earlier
versions.

**Comment by jschwartzenberg** [comment]
It hangs with 2.0pre6.1-dev. I don't know if the difference between the hang & crash would be relevant too?

**Comment by stsp** [comment]
Even the difference between
hang and crash may give some clue.
But better to bisect to 1.4 where it
definitely worked.

**Comment by jschwartzenberg** [comment]
Is there a trick for this one?
```
checking for stack protector disabled... no
configure: error: Cannot compile dosemu with stack protector enabled
```

**Comment by stsp** [comment]
Try `CFLAGS=-fno-stack-protector ./default-configure`

**Comment by jschwartzenberg** [comment]
Yeah just figured that out :) It's building!

**Comment by jschwartzenberg** [comment]
pre3 was still working ;)

**Comment by stsp** [comment]
Cool!

**Comment by jschwartzenberg** [comment]
The result of a naive bisect:
1565f8aa03eff3821302d320afdce90d8a17bcb2 is the first bad commit
commit 1565f8aa03eff3821302d320afdce90d8a17bcb2
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Nov 21 21:26:33 2015 +0300

    enable KVM by default on x64_64

:040000 040000 4c9414a09c55e3856d10db0dc13c8a5ac4e83c54 36d54308b8f18cb456abadef1226bdb4b83c8c86 M      src

I'll force cpuemu and look further.

**Comment by jschwartzenberg** [comment]
Seems it works with latest devel without kvm.

**Comment by stsp** [comment]
OK, that makes some sense.
So we have a somewhat wrong kvm
setup, likely some uninitialized values
there, but valgrind can't check that interface.
Same with volksvga?

**Comment by jschwartzenberg** [comment]
Yep, that one also works with cpuemu.

**Comment by stsp** [comment]
OK, so can anyone reproduce that and provide
an ssh access? This is a must-fix problem.
Having unreliable kvm is a no go.
Of course I will also try a few PCs at work.

**Comment by jschwartzenberg** [comment]
In case it helps:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               23
Model name:          Intel(R) Core(TM)2 Duo CPU     P9500  @ 2.53GHz
Stepping:            6
CPU MHz:             798.051
CPU max MHz:         2534.0000
CPU min MHz:         800.0000
BogoMIPS:            5054.32
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            6144K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm pti tpr_shadow vnmi flexpriority dtherm
```

**Comment by stsp** [comment]
Mine was AMD where it initially crashed and
now works. So I don't think this is related to CPU.

**Comment by jschwartzenberg** [comment]
Could this be related to the FPU issue #976?

**Comment by stsp** [comment]
Difficult to say.
I wouldn't bet on that because
such old software rarely uses FPU.
And my volksvga game IIRC didn't
too.
Is this still reproducible?

**Comment by jschwartzenberg** [comment]
Yes, DOSEMU2 crashes when running `carrier` here.

**Comment by stsp** [comment]
How to get that tested?
Still no way of cloning that setup
or bringing up an ssh access?

**Comment by jschwartzenberg** [comment]
It's not so easy yeah. Is there a log I could provide?

**Comment by stsp** [comment]
Is this a pic_revert problem?

**Comment by stsp** [comment]
Likely a duplicate of #986
