### ISSUE TITLE
Mouse range restricted

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#132]
This is DOSEMU2 on Ubuntu 12.04 LTS 32-bit, using "vm86" CPU VM.

When running Breadbox Ensemble (aka Geoworks Ensemble), I can't move the mouse over the whole screen. The range seems to be restricted to approximately 640x200 pixels. This happens with different video resolutions and drivers like standard VGA or VESA.

I've played with the options of "emumouse", but it made no difference. The default internal resolution could be seen suspected, because it match more or less the restriction I observed...

I've did a bisect and came to the following commit where the problem started to appear:

737e569e720fe3b2c43f7c4f4480ea2c1e4facee is the first bad commit
commit 737e569e720fe3b2c43f7c4f4480ea2c1e4facee
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Oct 17 01:51:45 2015 +0300

    int: stop revectoring ints e6 and e7 (from Bart's patch at PR #90)

:040000 040000 5e2e94e98051bb078ebbae75436209efe9498c01 e1fe9ddbc0ca41b28dfb762ae66de25cc4d1c226 M	src

The last revision which worked was "0a3364cd7abb291be5ae2b5bbb23f1db0b40f05c".

I tried to revert that changes on head, but was unsuccessful to compile it due to missing declaration or my inabillity...

Any idea what I can test more or how that problem can be resolved ?

**Comment by stsp** [comment]
Thanks for bisecting, this is very helpful.
It would be good to also:
1. Make sure same happens with mouse grab (Ctrl-Alt-Home)
2. Provide an URL to the program so that the
problem can be reproduced
3. Try the "kvm" branch (without enabling kvm itself)

Unfortunately we are currently very busy with adding
the new regressions, but having the bisected commits
will definitely help when the bugfixing time comes.

**Comment by stsp** [comment]
By the way, dosemu2 supports the native
mouse driver - you can use it as a work-around.
Try $_com1 = "mouse"
and then load mouse.com under DOS.

**Comment by bolle732** [comment]
The mouse is working with mouse grab, I can move the cursor over the whole screen when in grab. Releasing the mouse grab returns to the restrictet range. Thank you for this input !

The behaviour with the current KVM branch is the same, no difference.

I tried setting $_com1 = "mouse" and using different mouse drivers it in Ensemble. But didn't find a working configuration without the mouse grab. Sometimes, the restricted area wasn't in the upper left corner, but changed the location, depending where I entered with the mouse cursor into the DOSEMU window. This is all with SDL2. I can't use X anymore, as this crash my X-server (automatically restart of it).

Regarding a download link, there are shareware versions around, but all of them has the "fast CPU bug". This means, they crash on startup under DOSEMU on any recent (too fast) hardware. Maybe you remember my slowdown patch some time ago which works for all this versions, but not for Turbo Pascal applications...

I do my tests with Breadbox Ensemble 4.13, which has the fast CPU bug fixed, but unfortunately isn't free. Will see, if it's possible to donate a version to the development team. But I don't know how the company is going now, as there has been an incident lately.

So for now, I think this is of low priority and therefore can wait. I will keep an eye on it and maybe will find some more time to do further tests and experiments.

**Comment by stsp** [comment]
Then I tend to classify this as a bad report.
The commit you pointed, should not affect
only the non-grab mode without affecting grab
mode. Please check multiple times that your
bisect was good.
Yes, native mouse driver work only in grab mode
too; you can also use Ctrl-Alt-f to get grab+fullscreen.

OK, I vaguely remember the patch. You haven't
posted the results of testing it on pascal's apps.
In any case, if you are still interested in a slowdown
patch, my suggestion for dosemu2 would be as
follows:

1. If slowdown is enabled, use "vm86sim" mode,
ignoring the $_cpu_vm, $_cpu_emu and all other
relevant options. dosemu2 have a very good CPU
emulator, which was not the case when you posted
your patch (but to not steal other's credits, dosemu1
in its last releases got it in quite a good state too,
from which I could take off).
2. The more slowdown is requested, the fewer
instructions you allow the cpuemu to interpret,
before returning to dosemu's main loop.

With these ideas, I expect the patch to be quite
simple and effective; possible for applying.
Likely no need at all to estimate the time, do small
sleeps, and all the other trickery.

**Comment by bolle732** [comment]
Short answer as I need more time to verify everything again.

I wrote the result about the Pascal apps, that the slowdown didn't helped there :( Don't know why you missed my answer.

I did the bisect like this:

$ git bisect start
$ git bisect good c43ef4bd2d944f76a62f05a566df26d64d6b6d35
$ git bisect bad ff9141c6cf8041c68c3a682d8479db2ddd7bcf4a

:LOOP
$ make realclean
$ ./autogen.sh
$ ./default-configure
$ make
$ sudo make install
Manual test
$ git bisect <RESULT>
:NEXT

$ git bisect reset

After that, I tested with git checkout <COMMIT> of the last good one and first bad one to verify.

I'm not a git expert and there is a good chance, that I did something the wrong way. Even for me when checking the changes, I can't see any direct relation to my problem :(

I will retry the whole again. But will wait until you finished the merges, as the last state isn't compiling right now.

**Comment by stsp** [comment]
> I wrote the result about the Pascal apps, that the slowdown didn't helped there :(
> Don't know why you missed my answer.

Likely just forgot. This was long ago.

When you do "git bisect", git will eventually tell
you explicitly "the first bad commit is this:".
Until it did, the bisect is incomplete.

> But will wait until you finished the merges, as the last state isn't compiling right now.

Please be specific. What does not compile?

**Comment by bolle732** [comment]
Yes,  as written in my initial post, git told me that the referenced commit is bad.

I did a completely new checkout (still on i386):
```
$ git clone https://github.com/stsp/dosemu2.git .
$ make realclean
$ ./autogen.sh 
$ ./default-configure
$ make
```
Which produced the following error:
```
gcc -Wl,-warn-common  -rdynamic -o ../2.0-pre4/bin/dosemu.bin emu.o \
	   -Wl,--whole-archive lib/libbase_video.a lib/libbase_dev_vga.a lib/libbase_async.a lib/libarch_linux_async.a lib/libarch_linux_mapping.a lib/libbase_misc.a lib/libbase_misc_libpcl.a lib/libbase_dev_misc.a lib/libemu-i386.a lib/libemu-i386_simx86.a lib/libbase_speaker.a lib/libbase_dev_pic.a lib/libdosext_dpmi.a lib/libdosext_dpmi_msdos.a lib/libdosext_mfs.a lib/libdosext_misc.a lib/libbase_init.a lib/libbase_serial.a lib/libbase_mouse.a lib/libbase_dev_dma.a lib/libtools_debugger.a lib/libdosext_net.a lib/libbase_dev_sb16.a lib/libbase_sound.a lib/libdosext_drivers.a lib/libbase_bios.a lib/libplugin_extra_charsets.a lib/libplugin_translate.a lib/libplugin_translate_charsets.a lib/libplugin_commands.a lib/libplugin_kbd_unicode.a lib/libplugin_midimisc.a -Wl,--no-whole-archive -lpthread -ldl -lm -lrt 
lib/libdosext_dpmi.a(dpmi.o): In function `dpmi_control':
dpmi.c:(.text+0x1f7c): undefined reference to `indirect_dpmi_transfer'
collect2: ld returned 1 exit status
make[2]: *** [../2.0-pre4/bin/dosemu.bin] Error 1
make[2]: Leaving directory `/home/DOM/user/Entwicklung/dosemu2/src'
make[1]: *** [dosemu] Error 2
make[1]: Leaving directory `/home/DOM/user/Entwicklung/dosemu2/src'
make: *** [default] Error 2
```
I checked the file 'dpmi.c'.
```c
#if !DIRECT_DPMI_CONTEXT_SWITCH
static int in_indirect_dpmi_transfer;

__attribute__((noreturn))
static void indirect_dpmi_transfer(void)
{
  in_indirect_dpmi_transfer++;
  asm volatile ("\t hlt\n");
  __builtin_unreachable();
}
#endif
```
It seems that the #if does not work on my machine. If I remove it, the compile finishes.

The function call to 'indirect_dpmi_transfer' is enclosed like this:
```c
#if defined(__i386__) || !DIRECT_DPMI_CONTEXT_SWITCH
    /* Note: for i386 we can't set TF with our speedup code */
    indirect_dpmi_transfer();
#endif
```
Could it be, that the above #if should be done with && instead of || or the #if around the function 'indirect_dpmi_transfer' should be extended with `__i386__` ? Or what would be the correct way ?

**Comment by stsp** [comment]
Thanks!
The correct way (add __i386__) would be for me
to check the i386 builds eventually...

**Comment by bolle732** [comment]
That's great, the fix works for me too ;-)

Regarding a freely usable Breadbox Ensemble:
I could put together a version from purly public sources which runs under DOSEMU. This is a combination of a development version (Windows NT based) with drivers (DOS based) from another demo version. But first, I'll have to verify if it's ok providing this as a public download. If I can, then you could reproduce the initial problem about the mouse.

**Comment by stsp** [comment]
Well, you need to do that _only_ if the commit
you point to, really breaks what you say it does.
So please do that only if you verified everything
carefully multiple times, or all is in vain.

**Comment by bolle732** [comment]
Ok, is it possible to confirm the git and build commands I used above for bisecting are ok ? I'm using git very rarely. Mostly to checkout the current state of a program to compile and install it.

Is it also correct to switch to a specific commit with the following command ?
```$ git checkout <COMMIT>```

If yes, then I should be able to reproduce the good and bad state with:
```$ git checkout <LAST_GOOD_COMMIT>```
```$ git checkout <FIRST_BAD_COMMIT>```

I'm a little bit low on free time currently. So I do this all before and in the middle of my work day.

**Comment by stsp** [comment]
Yes, please reproduce it with "git checkout".

**Comment by bolle732** [comment]
Now I've done the same tests on another computer with Ubuntu 12.04 32-bit PAE. The results are the same :(

```$ git checkout 737e569e720fe3b2c43f7c4f4480ea2c1e4facee```
Run make realclean, autogen.sh, default-configure, make and make install.
-> The mouse is jailed into a part of the screen

```$ git checkout 0a3364cd7abb291be5ae2b5bbb23f1db0b40f05c```
Run make realclean, autogen.sh, default-configure, make and make install.
-> The mouse can be used fine

I really can not explain, as you wrote, the changes shouldn't be related to that problem.

**Comment by stsp** [comment]
When testing, please try enabling/disabling
grab multiple times to make sure the result
is consistent. If so, we'll need this prog for testing.

**Comment by stsp** [comment]
enabling/disabling grab is Ctrl-Alt-Home or Ctrl-Alt-f

**Comment by stsp** [comment]
Ok, after reproducing the problem, I have to
admit that you are right: this patch breaks mouse
sensitivity somehow... :(
And there are additional breakages that I can
reproduce with your program.

**Comment by stsp** [comment]
And another commit that introduces a stability
problem for your prog, is... this??? 2dae432f
Wtf.

**Comment by stsp** [comment]
Seems incompatible with dosemu's ems.sys.

**Comment by bolle732** [comment]
Thank you for the tests and findings. It's good for me, you could reproduce the mouse problem.

The other incompatibilities hasn't shown up to me right now. That it has a problem with "ems.sys" is new to me.

I'm using different PC/GEOS versions (as the system is called) since many years with DOSEMU and FreeDOS, but not this exact version you could try with it, which is intended running under NTVDM of Windows for debugging with the debugger called SWAT. Maybe I can provide you the other (consumer) version for comparision which is in use by many others too.

**Comment by stsp** [comment]
mouse problem is now fixed.

**Comment by stsp** [comment]
Your program crashes when EMS frame is set to e400.
This was a default value in dosemu for 10+ years, but
its non-standard so I set it back to e000.
It would be nice if you can fix your program though.

**Comment by bolle732** [comment]
I can confirm that the mouse problem is fixed. Tested on 2 machines. Thank you very much!

Regarding EMS, I will make some tests. I didn't used it in favor of XMS. Must be for more then 10 years... How the time is going on ;-)

**Comment by stsp** [comment]
> Regarding EMS, I will make some tests. I didn't used it in favor of XMS.

I think your program uses it.
In fact, it seems to crash before even mapping the
page above f0000. It just asks for the current mapping
layout and crashes if the mappable page exists above f0000
(which is the case when the base page starts at e4000).
I think there is a bug somewhere in that prog.
But its not a big deal to set it back to e0000, the only
disadvantage is more fragmentation in UMB.

**Comment by bolle732** [comment]
Yes, I have the same error with a relocated EMS frame.

Netherless, I found a documentation from Newdeal, which produced the GEOS Versions in the late 90s and early 2000. The EMS support is done for version 3.0. See [here](http://www.geos-infobase.de/ND_DOCS/210.HTM)

> When in the presence of EMS (expanded memory), our software takes the 64K page frame provided by
> a 3.0-compliant EMS manager and maps 3 16K pages to the lower 48K and gives it to the system in the
> same way as upper memory is used -- those 48K are parceled out automatically among the
> applications as requested and they never know the difference. The remaining 16K page is used for
> swapping, with data being copied to the 16K page until no more will fit, at which point the current EMS
> page that is mapped there is mapped out and another EMS page from the set the software allocated at
> start-up is mapped in its place, and the swapping continues. The software doesn't use the expanded
> page frame offered by some EMS 4.0-compliant managers and boards.

**Comment by stsp** [comment]
I think this still doesn't explain the crash.
Why it crashes if "The remaining 16K page" is at f0000,
is unclear.
