### ISSUE TITLE
dosemu-2.0pre1-gc1ea267 not compile on Centos 6/i386 (SDL1.2 problem?)

### ISSUE THREAD

**Issue by fhanzlik** [stsp/dosemu2#19]
Trying build dosemu-2.0pre1-gc1ea267 on Centos 6.6 i686, it ends with error:
...
sh: git: command not found
make[2]: Entering directory `/home/hanzlik/rpmbuild/BUILD/dosemu-2.0pre1/src/commands'
gcc -c -MP -MMD -I../../src/include -I../../src/plugin/include   -o isemu.o isemu.S
gcc -Wl,-warn-common  -Wl,-Ttext,100,-e,_start16,--oformat,binary -nostdlib -s -o ../../g../commands/isemu.com isemu.o
chmod -x ../../g../commands/isemu.com
gcc -c -MP -MMD -I../../src/include -I../../src/plugin/include   -o mgarrot.o mgarrot.S
In file included from ../../src/plugin/include/plugin_config.h:4,
                 from ../../src/include/config.h:220,
                 from ../../src/include/macros86.h:7,
                 from mgarrot.S:18:
../../src/include/../plugin/sdl/config/plugin_config.h:1:46: error: ../plugin/sdl/include/sdl_config.h: No such file or directory
make[2]: *** [mgarrot.o] Error 1
make[2]: Leaving directory `/home/hanzlik/rpmbuild/BUILD/dosemu-2.0pre1/src/commands'
make[1]: *** [commands] Error 2
make[1]: Leaving directory `/home/hanzlik/rpmbuild/BUILD/dosemu-2.0pre1/src'
make: *** [default] Error 2
...

Also, it seems there be several time called 'git', which IMO should not be mandatory for package building (but maybe it's absence isn't problem).
Attached are some outputs from configure and make phase - I renamed this .tar.gz to .png, as
github require ;)
Maybe this error occurs only when there is SDL-1.2 present (Centos 6/RHEL 6 has not SDL 2.0 in repos, only v1.2). Is possible build dosemu with SDL 1.2?

![dosemu-2 0pre1-gc1ea267 tgz](https://cloud.githubusercontent.com/assets/9540755/6201010/202b798a-b493-11e4-9b46-0d9b9022f38a.png)

**Comment by fhanzlik** [comment]
20150215.g1fa5fef compile (and seems working) well. SDL plugin is not compiled.
Thanks.
